# MR-AVI/setup.cfg

[metadata]
# --- Package details ---
name = instant-aiv
version = 0.1.0
author = Juan Toscano
author_email = juan_toscano@brown.edu
description = A Python package for Instant AIV processing.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/jdtoscano94/Instant_AIV
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Intended Audience :: Science/Research

[options]
# --- Package discovery ---
package_dir =
    = src
packages = find:
python_requires = >=3.9

# --- DEPENDENCIES ---
install_requires =
    numpy
    scipy
    pandas
    matplotlib
    optax
    h5py
    pyDOE     
    tqdm
    scikit-learn # 
    opencv-python # 
[options.packages.find]
where = src